### ISSUE TITLE
Consider using command palette instead of context menu

### ISSUE THREAD

**Issue by moshfeu** [galElmalah/scaffolder-vscode#4]
Context menu usually meant to run a command with a context of the selected file / folder.
The extension does nothing with the selected file so maybe the [command palette](https://code.visualstudio.com/api/extension-guides/command#creating-a-user-facing-command) (with shortcut option maybe) is more suitable.

**Comment by galElmalah** [comment]
It does, the template will be generated inside the folder you clicked on or in the same folder as the file you clicked.
I do need to create a new command for the "GitHub remote template" feature and the command palette will be a great fit there 😄

**Comment by moshfeu** [comment]
Nice! Didn't notice. Maybe it should be on click on folders only to make it more clear.
Also, consider not to show this context menu if the project has no `scaffolder` folder.

**Comment by galElmalah** [comment]
Thanks, I'll think about it 😃
